baseURL = 'https://amelielabs.io/docs/'
languageCode = 'en-us'
title = 'amelie'
theme = 'hugo-book'

[params]
  BookSection = '/'
  BookSearch = false
  BookRepo = 'https://github.com/amelielabs/amelie-docs'
  BookEditPath = 'edit/main'

[markup]
  [markup.highlight]
    noClasses = false

  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

