# Amelie theme is based on the hugo-book theme by Alex Shpak.

name = "Amelie"
license = "MIT"
licenselink = "https://github.com/alex-shpak/hugo-book/blob/master/LICENSE"
description = "Amelie documentation theme"
homepage = "https://github.com/alex-shpak/hugo-book"
demosite = "https://hugo-book-demo.netlify.app"
tags = ["responsive", "clean", "documentation", "docs", "flexbox", "search", "mobile", "multilingual", "disqus"]
features = []
min_version = "0.68"

[author]
  name = "Alex Shpak"
  homepage = "https://github.com/alex-shpak/"
